In [1]:
# Write a function so that the columns of the output matrix are powers of the input
# vector. The order of the powers is determined by the increasing boolean argument. Specifically,
# when increasing is False, the i-th output column is the input vector raised element-wise
# to the power of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
# Theophile Vandermonde.

def Alexandre(N,Bol):
  import numpy as np
  x=np.array([1,2,3,5])

  if (len(Bol) == 0 or Bol =='False'):
    check=''   
  else:
    check='True'  

  if N == 0:
    Num=len(x)
  else:
    Num=N

  
  print(np.vander(x,Num,increasing=check)) 

print('Vector with no length and Decreasing display')
Alexandre(N=0,Bol='')
print('Vector with no length and Increasing display')
Alexandre(N=0,Bol='True')
print('Vector with length and Decreasing display')
Alexandre(N=3,Bol='')
print('Vector with length and Increasing display')
Alexandre(N=3,Bol='True')
print('Vector with no length and Decreasing display')
Alexandre(N=0,Bol='False')
print('Vector with length and Decreasing display')
Alexandre(N=3,Bol='False')

Vector with no length and Decreasing display
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
Vector with no length and Increasing display
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
Vector with length and Decreasing display
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
Vector with length and Increasing display
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]
Vector with no length and Decreasing display
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
Vector with length and Decreasing display
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
